# Generated by Django 4.0 on 2022-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Creation Date'),
        ),
    ]
