# Generated by Django 4.0 on 2022-03-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Date')),
                ('comment_name', models.CharField(max_length=255, verbose_name='Name')),
                ('comment_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(max_length=255, verbose_name='Comment')),
                ('comment_publicated', models.BooleanField(verbose_name='Publicated')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User')),
            ],
        ),
    ]
