# Generated by Django 4.0 on 2022-03-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Date')),
                ('title_post', models.CharField(max_length=255, verbose_name='Title')),
                ('content_post', models.TextField(verbose_name='Content')),
                ('excerto_post', models.TextField(verbose_name='Excerto')),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Image')),
                ('publicated_post', models.BooleanField(default=False, verbose_name='Publicated')),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='Author')),
                ('category_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='category.category', verbose_name='Category')),
            ],
        ),
    ]
